config/routes.rb
Crm::Application.routes.draw do

  devise_for :users , :controllers => { :registrations => "users/registrations" }
  match 'users/all' => "users#all"
  get "profile(/:id)" , to: "users#profile" , as: :profile
  match 'search' => "users#search"


  authenticated do 
    root to: 'dashboard#index'
  end

  root to: "static_page#landing" 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # attr_accessible :title, :body 
  acts_as_taggable
  acts_as_taggable_on :skills, :interests
  self.per_page = 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  
  def home
    
  end

end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def landing
  end

  def about
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected
    def sign_up_params
      params.require(:user).permit(:first_name, :last_name, :title, :company , :email, :password, :password_confirmation,
          :phone, :address, :city, :state, :zip, :linkedin_url ,:facebook_url, :twitter_url , :skill_list)
    end

    def account_update_params
      params.require(:user).permit(:first_name, :last_name, :title, :company , :email, :password, :password_confirmation,
          :current_password,:phone, :address, :city, :state, :zip,:linkedin_url, :facebook_url, :twitter_url , :skill_list) 
    end

    def whiltelist_params
      params
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def all
    @users = User.paginate(:page => params[:page])
  end

  def search
    @skill = params[:q]
    @users = User.tagged_with(@skill).paginate(:page => params[:page])
    respond_to do |format|
      format.html 
      format.js
    end
  end

  def profile
    @user = if params[:id].present?
              begin
                User.find(params[:id])
              rescue Exception => e
                nil
              end
            else
              current_user
            end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users/registration_helper.rb
module Users::RegistrationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.haml
This will became the dashboard

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Crm"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    / = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "CRM" , root_path , class: 'brand'
          .container.nav-collapse
            - if user_signed_in?
              %ul.nav.pull-right
                %li.dropdown
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                    Setting
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      = link_to "Update Information" , edit_user_registration_path
                    %li
                      %a{:href => "#"} Something else here
                    %li.divider
                    %li
                      %a{:href => "#"} Separated link
                = menu_divider
                %li= link_to "Sign out", destroy_user_session_path , method: :delete
            - else
              %ul.nav.pull-right
                %li= link_to "Sign in" , new_user_session_path
                %li= link_to "Register" , new_user_registration_path

    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Quick Navigation
              - if user_signed_in?
                %li= link_to "Profile", profile_path
              %li= link_to "All Users", users_all_path
              %li= link_to "Search", search_path
        .span9
          = bootstrap_flash
          = yield
      %footer
        %hr
        %p.text-center &copy; Company 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/static_page/about.html.haml
%h1 StaticPage#about
%p Find me in app/views/static_page/about.html.haml

app/views/static_page/landing.html.haml
%h3 About This CRM Web App
%p This web app is a CRM (customer candidate relationship manager) exclusivily for indipendent recruiters and boutique recruitment firms. A way to save and find candidates with specific keywords/tags that are saved within your database. We charge a monthly membership fee per user that signs up for an account.

%ul
  %li Minimalistic
  %li Beautiful
  %li Useful

%h5 The biggest insperation to draw from are:
%ul
  %li LinkedIn.com > Network > Contacts
  %li HighRiseHQ.com and BaseCamp.com

%h3 Features
%h5 Import multiple candidates at once from the following options
%ul
  %li Excel
  %li LinkedIn
  %li Outlook
  %li vCard
  %li Resumes (zip folder for multiple resumes) - when you add a candidate by uploading a resume a profile will automatically be created. This will including the candidates full name, phone number, address email and resumes (all info from header).
Search for candidates by:
Keywords within their resumes
Keywords/ Tags in their profile/quick view
Pics
Pull pictures from candidates linkedin profile, fb, etc.
Browers
Web App must work on all browsers such as Chrome, Firefox, Safari, Internet Explorer, etc.
Devices
Must work on both PC and Mac.
%hr

E-mail to CRM as a note
Be able to forward an email to the CRM, and have the email stored as a note in the candidates profile.
%hr

E-mail resume attachment to create a profile.
Be able to forward an email with a attached resume to the CRM, and have the CRM automatically create a new profile for that candidate.
%hr

Attachments to candidate profile
Be able to attach word and pdf documents to candidates profile.
%hr

Select candidates from a seach result that you'd like to send one mass email to. When you send it will send all of the emails to the BCC field of a new Outlook email.
%hr
Resume to email attachment
click on "send resume to email" and a new outlook email will open up with the candidates resume attached.

app/views/users/_user.html.haml
= link_to  "#{user.first_name} #{user.last_name}" , profile_path(user.id)
%br
= user.title
%br
= user.company
%br

= user.email
%br
= user.phone
%hr

app/views/users/all.html.haml
= render @users
= will_paginate @users 

app/views/users/profile.html.haml
- if @user.nil?
  %p User didn't exist
- else 
  = render "user" , user: @user

app/views/users/search.html.haml
%h2 Search User based on keywords and skills

%form.form-search
  .input-append
    %input.search-query{:type => "text" , :name => "q" , placeholder: 'rubyonrails, aws,..' , value: @skill}/
    %button.btn{:type => "submit"} Search

%hr
#result
  %h3= "#{pluralize(@users.count, 'result')} found"
  .content
    = render @users
  .pagination
    = will_paginate @users

app/views/users/search.js.erb
$("#result h3").html("<%= j "#{pluralize(@users.count, 'result')} found"  %>");
$("#result .content").html("<%=j render @users %>");
$("#result .pagination").html("<%=j will_paginate @users  %>");

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>